create table if not exists public.historico (
  id bigint generated by default as identity primary key,
  reserva_id text not null,
  cliente text,
  empreendimento text,
  unidade text,
  analista_id bigint,
  analista_nome text,
  situacao_id integer,
  situacao_nome text,
  resultado text,
  data_fim timestamptz not null default now()
);

alter table public.historico add column if not exists analista_nome text;
alter table public.historico add column if not exists situacao_id integer;
alter table public.historico add column if not exists situacao_nome text;

create index if not exists idx_historico_data_fim
  on public.historico (data_fim desc);

create index if not exists idx_historico_analista_data
  on public.historico (analista_id, data_fim desc);

create index if not exists idx_historico_reserva
  on public.historico (reserva_id);