create table if not exists public.logs_transferencias (
  id bigint generated by default as identity primary key,
  reserva_id text not null,
  analista_origem_id bigint not null,
  analista_origem_nome text,
  analista_destino_id bigint not null,
  analista_destino_nome text,
  situacao_id integer,
  situacao_nome text,
  cliente text,
  empreendimento text,
  unidade text,
  motivo text,
  data_transferencia timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists idx_logs_transferencias_data
  on public.logs_transferencias (data_transferencia desc);

create index if not exists idx_logs_transferencias_reserva
  on public.logs_transferencias (reserva_id);
