-- Criar tabela de administradores
create table if not exists public.administradores (
  id bigint generated by default as identity primary key,
  username text not null unique,
  senha text not null,
  email text,
  ativo boolean default true,
  data_criacao timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Criar índice para buscas rápidas por username
create index if not exists idx_administradores_username
  on public.administradores (username);

-- Inserir admin padrão (senha: Admin@2026 - hash já gerado)
insert into public.administradores (username, senha, email, ativo)
values (
  'admin',
  'pbkdf2_sha256$310000$/izrCfgDdk2EGrQj7aQ3Dw==$LhM9HEmoq71PxXArpRpGZtp+nL35zaLcMQYxL3kErQg=',
  'admin@vcaconstrutora.com.br',
  true
)
on conflict (username) do update set
  senha = excluded.senha,
  updated_at = now();
