-- 006_logs_sessoes_revogadas_schema.sql
-- Cria tabela de auditoria oficial para revogacoes de sessao.

create table if not exists public.logs_sessoes_revogadas (
  id bigint generated by default as identity primary key,
  actor_admin_id bigint not null,
  actor_admin_username text,
  actor_admin_email text,
  target_role text not null check (target_role in ('admin', 'analyst')),
  target_user_id bigint not null,
  target_user_name text,
  target_user_email text,
  reason text not null default 'manual',
  new_session_version integer not null,
  revoked_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists idx_logs_sessoes_revogadas_revoked_at
  on public.logs_sessoes_revogadas (revoked_at desc);

create index if not exists idx_logs_sessoes_revogadas_actor
  on public.logs_sessoes_revogadas (actor_admin_id, revoked_at desc);

create index if not exists idx_logs_sessoes_revogadas_target
  on public.logs_sessoes_revogadas (target_role, target_user_id, revoked_at desc);
