create table if not exists public.sugestoes_melhoria (
  id bigint generated by default as identity primary key,
  titulo text not null,
  detalhes text not null,
  status text not null default 'Em análise',
  autor_analista_id bigint not null,
  autor_nome text not null,
  status_updated_by_admin_id bigint,
  status_updated_by_admin_nome text,
  status_updated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint sugestoes_melhoria_status_check check (
    status in (
      'Em desenvolvimento',
      'Em Planejamento',
      'Em análise',
      'Aprovado',
      'Aguardando Cliente',
      'Concluído'
    )
  )
);

create index if not exists idx_sugestoes_melhoria_created_at
  on public.sugestoes_melhoria (created_at asc);

create index if not exists idx_sugestoes_melhoria_status
  on public.sugestoes_melhoria (status);
